### ISSUE TITLE
403 when pushing

### ISSUE THREAD

**Issue by samuelcolvin** [carloscastrojumo/github-cherry-pick-action#12]
See [this build](), when using this action I'm getting

The following error:

```
Run carloscastrojumo/github-cherry-pick-action@v1.0.1
  with:
    branch: 1.10.X-fixes
    token: ***
    committer: GitHub <noreply@github.com>
    author: samuelcolvin <samuelcolvin@users.noreply.github.com>
  env:
    GITHUB_TOKEN: ***
Cherry pick into branch 1.10.X-fixes!
Configuring the committer and author
  Configured git committer as 'GitHub <noreply@github.com>'
  /usr/bin/git config --global user.name samuelcolvin
  
  /usr/bin/git config --global user.email noreply@github.com
  
Fetch all branchs
  /usr/bin/git remote update
  
  /usr/bin/git fetch --all
  
Create new branch from 1.10.X-fixes
  /usr/bin/git checkout -b cherry-pick-[2](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:2)4122f24845af8fd[3](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:3)28ea672779af2e5ef[4](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:4)7e30d origin/1.10.X-fixes
  Switched to a new branch 'cherry-pick-24122f2484[5](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:5)af8fd328ea[6](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:6)[7](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:7)2779af2e5ef47e30d'
  branch 'cherry-pick-24122f24[8](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:8)45af8fd328ea67277[9](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:10)af2e5ef47e30d' set up to track 'origin/1.[10](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:11).X-fixes'.
  branch 'cherry-pick-24122f24845af8fd328ea672779af2e5ef47e30d' set up to track 'origin/1.10.X-fixes'.
Cherry picking
  /usr/bin/git cherry-pick -m 1 --strategy=recursive --strategy-option=theirs 24122f24845af8fd328ea672779af2e5ef47e30d
  Auto-merging demo.py
  [cherry-pick-24122f24845af8fd328ea672779af2e5ef47e30d b9cee8a] Merge pull request #[11](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:12) from samuelcolvin/cherry-pick3
   Author: Samuel Colvin <s@muelcolvin.com>
   Date: Tue Sep 20 18:21:05 2022 +0100
   1 file changed, 1 insertion(+), 1 deletion(-)
  Auto-merging demo.py
  [cherry-pick-24[12](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:13)2f24845af8fd328ea672779af2e5ef47e30d b9cee8a] Merge pull request #11 from samuelcolvin/cherry-pick3
   Author: Samuel Colvin <s@muelcolvin.com>
   Date: Tue Sep 20 [18](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:20):21:05 [20](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:22)[22](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:25) +0100
   1 file changed, 1 insertion(+), 1 deletion(-)
Push new branch to remote
  /usr/bin/git push -u origin cherry-pick-[24](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:27)122f24845af8fd328ea67[27](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:31)79af2e5ef47e30d
  remote: Permission to samuelcolvin/pydantic-sandbox.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/samuelcolvin/pydantic-sandbox/': The requested URL returned error: 403
  Error: The process '/usr/bin/git' failed with exit code 1[28](https://github.com/samuelcolvin/pydantic-sandbox/actions/runs/3092113765/jobs/5003010866#step:3:32)
```

My action file is [here](https://github.com/samuelcolvin/pydantic-sandbox/blob/24122f24845af8fd328ea672779af2e5ef47e30d/.github/workflows/cherry-pick.yml) and looks like:

```yaml
name: cherry-pick

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cherry_pick:
    runs-on: ubuntu-latest

    name: Cherry pick into 1.10.X-fixes

    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'cherry-pick-v1')

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cherry pick into 1.10.X-fixes
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: 1.10.X-fixes
```

I've also tried setting `token` in the `with` section, but same error.

From what I've read `secrets.GITHUB_TOKEN` should be available and should have suitable permissions.

What am I doing wrong?
