### ISSUE TITLE
Title and Body do not seem to be working

### ISSUE THREAD

**Issue by Pexeed** [carloscastrojumo/github-cherry-pick-action#145]
Hello! Thanks for the great action!

So I'm testing it before adding to my professional project and the PRs that are being created are not following the Title and Body that I set, here is the action implementation:

name: Auto Generate PRs marked as hotfix from Main to Version Branch
```
on:
  pull_request:
    branches: main

jobs:
  cherry_pick_to_version_branch:
    runs-on: ubuntu-latest
    name: Cherry pick into version branch
    if: ${{ contains(github.event.pull_request.labels.*.name, 'hotfix') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into version branch
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: v0.1
          title: "v0.1 - {old_title}"
          body: "Cherry picking #{old_pull_request_id} onto this branch"
          labels: |
            cherry-pick
          reviewers: |
            mobile
```

Another question I have, is there a way to put a regex instead of a fixed branch in the `branch` parameter?
Would be nice cause then we can use to create multiple PRs for all the active version branches.

Another thing I was wondering is if there is a way to add a check for a previously created PR, so it overwrites or deletes it, and then create the new one, to avoid creating multiple PRs.

Again, thanks for this action, very useful!
