### ISSUE TITLE
feature: Add {old_pull_request_body} and {old_pull_request_title}

### ISSUE THREAD

**Issue by hwhsu1231** [carloscastrojumo/github-cherry-pick-action#164]
### Feature Request

Hello, Maintainance Team.

I hope that github-cherry-pick-action can provide the following two special variables:

1. `{old_pull_request_body}`
2. `{old_pull_request_title}` (same as the `{old_title}`)

Because I would like to apply this GitHub Action in the following form:

```yml
      - name: Cherry Pick into 'source/git-master' branch
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'source/git-master'
          labels: 'cherry-pick, automerge'
          force: true
          title: |
            {old_pull_request_title}
          body: |
            {old_pull_request_body}

            Cherry-picked from #{old_pull_request_id}
```

Therefore, I would need a special variable to reference the body of the old pull request, `{old_pull_request_body}`.

As for `{old_pull_request_title}`, it's simply to make the naming more systematic.

### Version

- github-cherry-pick-action: `v1.0.10`
